### ISSUE TITLE
Failed to mount '/dev/sdd1 ; Failed to mount '/dev/sdd10'

### ISSUE THREAD

**Issue by umiddelb** [apritzel/pine64#2]
Although you image starts with a valid partition table, the filesystems seem to be unmountable.
Any ideas?

**Comment by apritzel** [comment]
Those partitions are just placeholders, they are actually not formatted (yet). One reason for that was to keep the image small, also I wanted to get it out of the door, so since they are not actually needed, I simply skipped them.
If you have a rootfs lying around somewhere, do a "mke2fs -t ext4 /dev/sdd10", then mount it and untar your archive there. If you actually have the rootfs as an ext{2,3,4} image already, you can simply "dd" it to the partition (assuming it's less than 960 MB), then "resize2fs /dev/sdd10" to adjust it's size.

**Comment by apritzel** [comment]
Oh, and if you care about sdd1: You can copy the content of the original Pine64 Android image's sdd1 into that (after "mkdosfs -T 32 /dev/sdd1" & mounting it). It didn't dare to copy their files, also it's mostly about the bootlogo only anyway AFAICS, so not really something I deeply care about ;-)

**Comment by umiddelb** [comment]
> If you have a rootfs lying around somewhere, do a "mke2fs -t ext4 /dev/sdd10", then mount it and untar your archive there.

I have two of them: https://www.dropbox.com/sh/eh42yu8vyiootpy/AABdmwKI0v7F_BD0wKI5mkrBa?dl=0

**Comment by apritzel** [comment]
Worked for me with the jessie image, just need to nuke the root password ;-)

**Comment by umiddelb** [comment]
no need to nuke anything, just use

debian/111111

for logging in. The debian user has sudo privileges.
For ubuntu, use

ubuntu/111111

What about the kernel modules and firmware blobs? Where can I find them in order to add them to the roofs?

**Comment by apritzel** [comment]
Please note that this first image is very early proof of concept. There are no modules at this point in time. For firmware blobs please relate to either Allwinner or the guys at Pine64.com.
The image is more meant to provide a starting point for further hacking activities by making it easier to run your own kernel on it.

**Comment by umiddelb** [comment]
You're right, it should be sufficient to bootstrap a running debian system.

Once I've succeeded building a Linux kernel from source I can copy /lib/modules and /lib/firmware to the rootfs.
